// Code generated by go2go; DO NOT EDIT.


//line stack2.go2:1
package main

//line stack2.go2:1
import "fmt"

//line stack2.go2:7
func main() {
	var s instantiate୦୦Stack୦string
	s.Push("test1")
	s.Push("test2")
	buf := s.Peek()
	fmt.Println(buf)
}

//line stack2.go2:13
type instantiate୦୦Stack୦string []string

//line stack2.go2:17
func (s *instantiate୦୦Stack୦string,) Push(value string,

//line stack2.go2:17
) {
	*s = append(*s, value)
}

func (s *instantiate୦୦Stack୦string,) Peek() string {
	rtn := (*s)[len(*s)-1]
	*s = (*s)[:len(*s)-1]
	return rtn
}

//line stack2.go2:25
type Importable୦ int

//line stack2.go2:25
var _ = fmt.Errorf
